defaults: &defaults
  type: pop                                 # pop OR imap
  server: mail.5skills.me                    # server hostname
  port:  995                                 # 993 for IMAPs
  ssl: true                                     # Remove if not using SSL
  username: phone_catcher@5skills.me        # Username
  password: @-.uub9PVz9U                    # Password
  receiver:                                 # ActionMailer that will receive mail
  use_login:                                # Required for GMAIL
  sleep_time:                               # Poll Frequency. 60 seconds by default
  authentication:                           # LOGIN, CRAM-MD5, PASSWORD (IMAP Only)

development:
  <<: *defaults
  # Override other values here
  
test:
  <<: *defaults
  # Override other values here
  
production:
  <<: *defaults
  # Override other values here