#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'
require File.dirname(__FILE__) + '/../config/boot'
require 'daemon'
require 'yaml'
require 'fetcher'

class MailFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{RAILS_ROOT}/config/mail.yml")
  @config = @config[RAILS_ENV].to_options
  
  @sleep_time = @config.delete(:sleep_time)
  def self.start
    puts "Starting MailFetcher"
    # Add your own receiver object below and specify fetcher subclass
    @fetcher = Fetcher::Pop.new({:receiver => IncomingMailFetcher}.merge(@config))

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
end

MailFetcherDaemon.daemonize